# -*- coding: utf-8 -*-
"""HealthChatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dInqXzGvjWOJez5AFLD0vZN_lpKABPXx

Step 1: Install the packages
"""

!pip install google-generativeai -quiet
!pip install ipywidgets --quiet
!pip install gradio --quiet

"""Step 2: Install the libraries"""

import google.generativeai as genai
import os
import ipywidgets as widgets
from IPython.display import display,Markdown
import gradio as gr

"""Step 3: Setup the Gemini API"""

# Configure API
genai.configure(api_key="")  # Replace this

# Reinitialize chat session (do NOT do this multiple times!)
model = genai.GenerativeModel("gemini-1.5-flash")
chat = model.start_chat()

"""Step 4: Chatbot"""

# Input and output widgets
user_input = widgets.Text(
    placeholder="Ask a health-related question...",
    description="You:",
    layout=widgets.Layout(width='100%')
)

output = widgets.Output()

def on_user_submit(sender):
    question = user_input.value.strip()
    if not question:
        return

    with output:
        display(Markdown(f"**You:** {question}"))
        display(Markdown("_AI Doctor is typing..._"))

    try:
        # Send message to Gemini
        response = chat.send_message(question)
        with output:
            display(Markdown(f"**AI Doctor:** {response.text}"))
    except Exception as e:
        with output:
            display(Markdown(f"**Error:** {str(e)}"))

    user_input.value = ""  # Clear input field

# Connect enter key
user_input.on_submit(on_user_submit)

# Display widgets
display(user_input)
display(output)

"""Step 5: GUI (optional)"""

